cart/urls.py
from django.urls import path
from .views import cart_summary, update_item, checkout, process_order

app_name = 'cart'

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('cart-summary/', cart_summary, name='cart-summary'),
    path('update_item/', update_item, name='update_item'),
    path('process_order/', process_order, name='process_order')

    ]

e_art/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from users.views import CustomLoginView, RegisterView, ResetPasswordView, ChangePasswordView
from users.forms import LoginForm
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-confirm/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
    path('', include('post.urls')),
    path('', include('cart.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import (file_upload, user_posts, explore, user_profile,
                    delete_view, modify_post, post_view)

app_name = 'post'

urlpatterns = [
    path('post/', file_upload, name='user-post'),
    path('explore/', explore, name='explore'),
    path('user/', user_posts, name='user-file'),
    path('profile/<str:pk>/', user_profile, name='user-profile'),
    path('<id>/delete/', delete_view, name='post-delete'),
    path('<id>/modify/', modify_post, name='post-modify'),
    path('post_view/<str:pk>/', post_view, name='post-view'),

]

cart/models.py
from django.db import models
from django.contrib.auth import get_user_model
from datetime import datetime

from post.models import Post
# Create your models here.

AuthUser = get_user_model()

class Order(models.Model):
    user = models.ForeignKey(AuthUser, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=100)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        shipping = False
        orderitems = self.orderitems.all()

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    
    item_type = models.CharField(max_length=7)
    product = models.ForeignKey(Post, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingModel(models.Model):
    user = models.ForeignKey(AuthUser, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    zipcode = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

cart/views.py
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
import json
from post.models import Post
from .models import Order, OrderItem, ShippingModel
from django.contrib import messages
from django.http import JsonResponse
import datetime
from .utils import  cart_data, cookie_cart, guest_order

# Create your views here.


def cart_summary(request):

    data = cart_data(request)
    cart_items = data['cartItems']
    items = data['items']
    order = data['order']

    context = {'items': items, 'order': order, 'cartItems': cart_items}
    return render(request, 'cart/cart_view.html', context)


def checkout(request):

    data = cart_data(request)
    cart_items = data['cartItems']
    items = data['items']
    order = data['order']

    context = {'items': items, 'order': order, 'cartItems': cart_items}
    return render(request, 'cart/checkout_view.html', context)


def update_item(request):
    data = json.loads(request.body)
    post_id = data['postId']
    action = data['action']

    user = request.user
    post = Post.objects.get(id=post_id)
    order, created = Order.objects.get_or_create(user=user, complete=False)
    order_item, created = OrderItem.objects.get_or_create(order=order, product=post)

    if action == 'add':
        order_item.quantity = (order_item.quantity + 1)
    elif action == 'remove':
        order_item.quantity = (order_item.quantity - 1)
 
    
    order_item.save()

    if order_item.quantity <= 0:
        order_item.delete()
    return JsonResponse('Item was added', safe=False)


def process_order(request):
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        user = request.user
        order, created = Order.objects.get_or_create(user=user, complete=False)

    else:
        user, order = guest_order(request, data)
        

    total = float(data['form']['total'])
    order.transaction_id = transaction_id
    if total == order.get_cart_total:
        order.complete = True
    order.save()

    ShippingModel.objects.create(
            user = user,
            order = order,
            address = data['shipping']['address'],
            city = data['shipping']['city'],
            zipcode = data['shipping']['zipcode'],
        )

        
    return JsonResponse('Payment complete!', safe=False)

cart/templates/cart/cart_view.html
{% extends 'users/base.html' %}

{% block title %} Cart {% endblock %}

{% block content %}

			<div class="form-upload">
				<table class="table">
					<tr>
						<th><h5>Items: <strong></strong>{{ order.get_cart_items }}</h5></th>
						<th><h5>Total:<strong> {{ order.get_cart_total|floatformat:2}}$</strong></h5></th>
						<th>
						</th>
					</tr>
				</table>
			</div>

			<table>
				<tr>
					<td> </td>
					<td>Item</td>
					<td>Price</td>
					<td>Quantity</td>
					<td>Item Type</td>
					<td>Total</td>
				</tr>
				</table>

				<div class="cart-row">
					<table>
                    {% for item in items %}
						<tr>
							<td><img class="row-image" src="{{ item.product.image.url }}"  width="50" height="50"></td>
							<td >{{ item.product.price|floatformat:2}}$</td>
							<td>{{ item.quantity }}<i data-post={{item.product.id}} data-action="add"class="fa-solid fa-angle-up update-cart " ></i>
							<i data-post={{item.product.id}} data-action="remove" class="fa-solid fa-angle-down update-cart"></i></td>
							<td>{{ item.item_type }}</td>
							<td>{{ item.get_total }}$</td>
						</tr>
						{% endfor %}
					</table>
				</div>
			<a  class="btn btn-outline-dark" href="{% url 'post:explore' %}"> Continue Shopping</a>
			<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'cart:checkout' %}">Checkout</a>
		</div>
</div>
{% endblock %}

cart/templates/cart/checkout_view.html
{% extends 'users/base.html' %}
{% block title %} CheckOut {% endblock %}

{% block content %}
<div class="container">
    <div class="summary">
        <div class="top">
            <h2>Order Summary</h2>
            {% for item in items %}
            <div class="items">
                <table>
                    <tr>
                        <td><img class="row-image" src="{{ item.product.image.url }}"  width="50"
     height="50"></td>
                        <td>{{ item.product.title }}</td>
                        <td>{{ item.get_total|floatformat:2}}$</td>
                        <td>{{ item.quantity }}</td>
                    </tr>
                </table>
            </div>
            {% endfor %}
        </div>
        <div class="bot">
            <p id="p1">Total Price: {{ order.get_cart_total|floatformat:2}}$</p>
            <p>Total Items: {{ order.get_cart_items }}</p>
        </div>

    </div>

    <div class="form">
        <form id="form">
            {% csrf_token %}
            <div id="user-info">
                User Info
                <hr>
                <div class="form-field">
                    <input required class="form-control" type="text" name="name" placeholder="Name..">
                </div>
                <div class="form-field">
                    <input required class="form-control" type="email" name="email" placeholder="Email..">
                </div>
            </div>
            <p>Shipping Info</p>
                  <hr>
            <div id="shipping">

                <div class="form-field">
                    <input  required class="form-control"type="text" name="address" placeholder="Address">
                </div>
                <div class="form-field">
                    <input required class="form-control" type="text" name="city" placeholder="City" >
                </div>
                <div class="form-field">
                    <input required class="form-control" type="text" name="zipcode" placeholder="Zip Code" >
                </div>
                <div class="form-field">
                    <input required class="form-control" type="text" name="country" placeholder="Country" >
                </div>
            </div>
            <hr>
            <input  id='form-button' class="btn" type="submit" value="Continue">
        </form>
            <div class="box-element hidden" id="payment-info">
                <small>PayPal Option</small>
                <div id="paypal-button-container"></div>
                <!-- <button id="make-payment">Make Payment</button> -->
        </div>
    </div>

</div>
    <script src="https://www.paypal.com/sdk/js?client-id=AbQWJDUClsS54Go0KsxymiVV8BSLku4kfXO3GlZEr5cwaBwcoQqN-us6b-PCNI1UNYHe3UhYzTqaBRvW&currency=USD"></script>
    <script>
        var total = '{{order.get_cart_total}}'
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: parseFloat(total).toFixed(2)
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(orderData) {
                    submitFormData()
                    // Successful capture! For demo purposes:
                    // console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                    // var transaction = orderData.purchase_units[0].payments.captures[0];
                    // alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

                    // Replace the above to show a success message within this page, e.g.
                    // const element = document.getElementById('paypal-button-container');
                    // element.innerHTML = '';
                    // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                    // Or go to another URL:  actions.redirect('thank_you.html');
                });
            }


        }).render('#paypal-button-container');
    </script>

    
    <script type="text/javascript">

        var total = '{{ order.get_cart_total|floatformat:2}}'

        if ( user != 'AnonymousUser'){
            document.getElementById('user-info').innerHTML = ''
            }

        var form = document.getElementById('form')

        form.addEventListener('submit', function(e){
            e.preventDefault()
            console.log('Form submited')
            document.getElementById('form-button').classList.add('hidden')
            document.getElementById('payment-info').classList.remove('hidden')
            })
        // document.getElementById('make-payment').addEventListener('click', function(e){
        //     submitFormData()
        // })


        function submitFormData(){
            console.log('PAYMENT BUTTON CLICKED')


            var userFormData = {
                'name':null,
                'email':null,
                'total':total,
            }

            var shippingInfo = {
                'address':null,
                'city':null,
                'zipcode':null,
                'country':null,
            }

            shippingInfo.address = form.address.value
            shippingInfo.city = form.city.value
            shippingInfo.zipcode = form.zipcode.value
            shippingInfo.country = form.country.value
            

            if (user == 'AnonymousUser'){
                userFormData.name = form.name.value
                userFormData.email = form.email.value
            }


            var url = '/process_order/'
            fetch(url,{
                method:'POST',
                headers:{
                        'Content-Type':'application/json',
                        'X-CSRFToken':csrftoken,
                        },
                body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo}
                    )
            })
            .then((response) => response.json())
            .then((data) => {
                           console.log('Success:', data);
                           alert('Transaction completed');

                           cart = {}
                           document.cookie = 'cart=' + JSON.stringify(cart) + ';domain=;path=/'
                           window.location.href = "{% url 'post:explore' %}"
                           })
        
                        }

    </script>

{% endblock %}