cart/urls.py
from django.urls import path
from .views import cart_summary, update_item, checkout, process_order

app_name = 'cart'

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('cart-summary/', cart_summary, name='cart-summary'),
    path('update_item/', update_item, name='update_item'),
    path('process_order/', process_order, name='process_order')

    ]

e_art/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from users.views import CustomLoginView, RegisterView, ResetPasswordView, ChangePasswordView
from users.forms import LoginForm
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-confirm/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
    path('', include('post.urls')),
    path('', include('cart.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import (file_upload, user_posts, explore, user_profile,
                    delete_view, modify_post, post_view)

app_name = 'post'

urlpatterns = [
    path('post/', file_upload, name='user-post'),
    path('explore/', explore, name='explore'),
    path('user/', user_posts, name='user-file'),
    path('profile/<str:pk>/', user_profile, name='user-profile'),
    path('<id>/delete/', delete_view, name='post-delete'),
    path('<id>/modify/', modify_post, name='post-modify'),
    path('post_view/<str:pk>/', post_view, name='post-view'),

]

post/models.py
from django.db import models
from django.contrib.auth import get_user_model
from PIL import Image
from django.conf import settings
from django.utils import timezone
from django.db import models
import os
from django.dispatch import receiver
from exiffield.fields import ExifField
from exiffield.getters import exifgetter
# Create your models here.
AuthUser = get_user_model()


class Post(models.Model):
    user = models.ForeignKey(AuthUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=19, decimal_places=2)
    image = models.ImageField(default=None, upload_to='users_posts')
    description = models.TextField(max_length=1000)
    date_publication = models.DateTimeField(auto_now_add=True)
    exif = ExifField(
        source='image',
    )

    def __str__(self):
        return self.title


    def publish(self):
        self.published_date = timezone.now()
        self.save()

def _delete_file(path):
   """ Deletes file from filesystem. """
   if os.path.isfile(path):
       os.remove(path)

@receiver(models.signals.post_delete, sender=Post)
def delete_file(sender, instance, *args, **kwargs):
    """ Deletes image files on `post_delete` """
    if instance.image:
        _delete_file(instance.image.path)
    

class ImageData(models.Model):
    post = models.OneToOneField(Post, on_delete=models.CASCADE)
    camera = models.CharField(default=None, max_length=100, null=True, blank=True)
    model= models.CharField(default=None, max_length=100, null=True, blank=True)
    aperture = models.CharField(max_length=100, default=None, null=True, blank=True)
    shutter_speed = models.CharField(default=None, max_length=100, null=True, blank=True)
    focal_length = models.CharField( default=None, max_length=100, null=True, blank=True)

    def __str__(self):
        return self.camera + "-" + self.post.title

post/forms.py
from django import forms
from .models import Post



class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'price', 'image', 'description', ]

post/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from post.models import Post
from users.models import Profile
from cart.models import Order
from cart.utils import cart_data
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# Create your views here.


@login_required()
def file_upload(request):

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            return redirect('/explore/')
    else:
        form = PostForm

    return render(request, 'post/post_form.html', {'form': form})


def explore(request):
    data = cart_data(request)
    cart_items = data['cartItems']
    posts = Post.objects.all()
    order_by = request.GET.get('sort')
    page = request.GET.get('page')
    paginator = Paginator(posts, 6)
    if order_by == 'a_z':
        posts = posts.order_by('title')
    elif order_by == 'z_a':
        posts = posts.order_by('-title')
    elif order_by == 'price_low':
        posts = posts.order_by('price')   
    elif order_by == 'price_high':
        posts = posts.order_by('-price')   
    elif order_by == 'date_old':
        posts = posts.order_by('date_publication')   
    else:
        posts = posts.order_by('-date_publication')
    
    # try:
    #     posts = paginator.page(page)
    # except PageNotAnInteger:
    #     posts = paginator.page(1)
    # except EmptyPage:
    #     posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'cartItems': cart_items}
    return render(request, 'post/post_list.html', context)


@login_required
def user_posts(request):
    posts = Post.objects.filter(user=request.user)
    return render(request, 'post/user_posts.html', {'posts': posts})


def user_profile(request, pk):
    profile = Profile.objects.filter(user_id=pk)
    posts = Post.objects.filter(user_id=pk)
    context = {'posts': posts, 'profile': profile}
    return render(request, 'post/profile_posts.html', context)


def post_view(request, pk):
    post = Post.objects.filter(id=pk)
    context = {'post': post,}
    return render(request, 'post/post_view.html', context)


def delete_view(request, id):
    context = {}
    obj = get_object_or_404(Post, id=id)

    if request.method == 'POST':
        obj.delete()
        return HttpResponseRedirect('/')

    return render(request, 'post/delete_view.html', context)


def modify_post(request, id):
    obj = get_object_or_404(Post, id=id)
    form = PostForm(instance=obj)

    if request.method == 'POST':
        form = PostForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    context = {'form': form}
    return render(request, 'post/modify_post.html', context)

post/templates/post/delete_view.html
{% extends 'users/base.html' %}
{% block title %} Delete Post {% endblock %}

{% block content %}
<div class="main">
    <!-- Create a Form -->
    <form method="POST">
        <!-- Security token by Django -->
        {% csrf_token %}
        Are you want to delete this item ?
        <input type="submit" value="Yes" />
        <a href="/">Cancel </a>
    </form>
</div>

{% endblock %}

post/templates/post/modify_post.html
{% extends 'users/base.html' %}
{% block title %} Modify Post {% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                <div class="container-fluid">
                    <div class="container-sm">
                      <div class="mb-3">
                            <label class="form-label">{{user.username}}</label>

                      </div>
                      <div class="mb-3">

                            {{form.as_p}}
                                         <button type="submit" class="btn btn-primary">Submit</button>

                    </div>
                </div>
            </form>
 {% endblock %}

post/templates/post/post_form.html
{% extends 'users/base.html' %}

{% block title %} Create Post {% endblock %}

{% block content %}
        <div class="form-upload">
            <header class="header"><a>CREATE NEW POST</a></header>
            <form method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                            <p>Title: {{form.title}}</p>
                            <p>Price: {{form.price}}</p>
                            <p>Upload image:{{form.image}}</p>
                            <p>Description: {{form.description}}</p>

                        <button type="submit" class="btn-profile">Submit</button>
            </form>
        </div>

{% endblock %}

post/templates/post/post_list.html
{% extends 'users/base.html' %}
{% block title %} Hello {% endblock %}

{% block content %}
<div class="filter" style="margin-top:50px;">
    <form action="{% url 'post:explore' %}">
        <span style="color:white;">Sort by:</span>
        <select name="sort">
          <option value="a_z">title(A-Z)</option>
          <option value="z_a">title(Z-A)</option>
          <option value="price_low">price(min-max)</option>
          <option value="price_high">price(max-min)</option>
          <option value="date_old">published-date(olrder-)</option>
          <option value="date_new">published-date(newest)</option>
          <input type="submit" value="Sort">
        </select>
      </form>
</div>
        <div class="grid-container infinite-container">
            {% for post in posts %}
                <div class="grid-item infinite-item">
                    <a href="{% url 'post:post-view' pk=post.pk %}"><img src="{{ post.image.url }}" class="card-img-top "></a>
                    
                    <div class="middle-top">
                        <div class="price"><p>${{post.price}}</p></div>
                    </div>
                    <div class="middle">
                        <div class="logo"><img src="{{post.user.profile.avatar.url}}" class="avatar" width="50px"></div>
                        <div class="user-name"><p>{{ post.user.username}}</p></div>
                        <div class="text"><p>{{ post.title }}</p></div>
                        
                    </div>
                </div>
                    {% endfor %}
                </div>
                {% if posts.has_next %}
                <a class="infinite-more-link" href="?page={{ posts.next_page_number }}"></a>
                {% endif %}
                <div class="d-flex justify-content-center" style="display:none;">
                    <div class="spinner-border" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>

            </div>

    <script src="/static/js/jquery-3.6.1.min.js"></script>
    <script src="/static/js/jquery.waypoints.min.js"></script>
    <script src="/static/js/infinite.min.js"></script>
    <script>
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            handler: function(direction) {

        },
        offset: 'bottom-in-view',

        onBeforePageLoad: function () {
        $('.spinner-border').show();
        console.log('i`m working')
        },
        onAfterPageLoad: function () {
        $('.spinner-border').hide();
        }

        });

    </script>
     
{% endblock %}

post/templates/post/post_view.html
{% extends 'users/base.html' %}

{% block title %} {{post.title}} {% endblock %}

{% block content %}

{% for post in post %}

<!-- <h1 style="text-transform:capitalize;">{{post.title}}</h1> -->

<div class="container1">
    <div class="img-container">
        <img class="card-img-top" src="{{ post.image.url}}">
    </div>
    <div class="detail-container">
        <div class="description-container">
            <h5>Description</h5>
            <p>{{post.description}}</p>
            <p>{{post.date_publication}}</p>
        </div>
        <div class="photo-info-container">
            <div class="photo-item"><img src="https://img.icons8.com/ios/50/null/camera--v3.png"/>
                <p>{{post.imagedata.camera}}<br>{{post.imagedata.model}}</p>
            </div>
            <div class="photo-item"><img src="https://img.icons8.com/ios-filled/50/null/frequency-f.png"/>
                <p>/{{post.imagedata.aperture}}</p>
            </div>
            <div class="photo-item"><img src="https://img.icons8.com/ios/50/null/focal-length.png"/>
                <p>{{post.imagedata.focal_length}}</p>
            </div>
            <div class="photo-item"><h3>Shutter</h3>
                <h3> Speed</h3>
                <p>{{post.imagedata.shutter_speed}}</p>
            </div>
            
            
            
            
            
        </div>
        <div class="user-container">
            <img src="{{post.user.profile.avatar.url}}" class="avatar" width="50px">
            <a href="{% url 'post:user-profile' pk=post.user.pk %}"><p>{{post.user.first_name}}
                 {{post.user.last_name}}</p></a>
                 <p>{{post.user.profile.bio}}</p>
        </div>
        <div class="button-container">
            <button data-post={{post.id}} data-action="add" type="submit" class="btn-profile update-cart">Add to cart</button>
        </div>
   </div>
</div>

{% endfor %}

<script>
    var modButton1 = document.getElementById('btn1')

    modButton1.addEventListener('click', function(){
        modButton1.classList.add('clicked')
        document.getElementById('btn2').classList.remove('clicked')
    })

    var modButton2 = document.getElementById('btn2')

    modButton2.addEventListener('click', function(){
        modButton2.classList.add('clicked')
        document.getElementById('btn1').classList.remove('clicked')
    })
        
  

</script>

{% endblock %}

post/templates/post/profile_posts.html
{% extends 'users/base.html' %}
{% block title %} he {% endblock %}

{% block content %}
    {% for user in profile %}
    <table>
        <tr>
            <th>{{user.user.username}}</th>
            <tr><img src="{{user.avatar.url}}"></tr>
        <td> {{user.bio}}</td>
        </tr>
        {% endfor %}

    </table>
            <div class="container">
            <div class="row">
                {% for post in posts %}

                <div class="col-sm-4 mb-3">
                    <div class="col-3 py-3">
                        <div class="card" style="width: 380px;">

                              <a href="{{ post.image.url }}"><img src="{{ post.image.url }}" class="card-img-top ratio ratio-1x1" width="300"></a>
                              <div class="card-body">
                                <h5 class="card-title">{{ post.title }}</h5>
                                <p class="card-text">Description:{{post.description}}</p>
                                <a href="#" class="btn btn-primary">Price: {{post.price}}$</a>

                              </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>

{% endblock %}

post/templates/post/user_posts.html
{% extends 'users/base.html' %}
{% block title %} Update {% endblock %}

{% block content %}

        <div class="grid-container">
                {% if posts %}
                    {% for post in posts %}
                        <div class="grid-item">
                                      <a href="{{ post.image.url }}"><img src="{{ post.image.url }}" class="card-img-top"></a>
                                      <div class="middle">
                                        <a href="{% url 'post:post-modify' id=post.id %} " class="btn-profile"> Modify</a>
                                        <a href="{% url 'post:post-delete' id=post.id %}" class="btn-profile">Delete</a>
                        </div></div>
                        {% endfor %}
                {% else %}
                <div class="container-fluid text-align: center;" id="post">
                    <h3 class="bg-primary"> You have no items.</h3>
                </div>
                {% endif %}
        </div>

{% endblock %}