cart/urls.py
from django.urls import path
from .views import cart_summary, update_item, checkout, process_order

app_name = 'cart'

urlpatterns = [
    path('checkout/', checkout, name='checkout'),
    path('cart-summary/', cart_summary, name='cart-summary'),
    path('update_item/', update_item, name='update_item'),
    path('process_order/', process_order, name='process_order')

    ]

e_art/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from users.views import CustomLoginView, RegisterView, ResetPasswordView, ChangePasswordView
from users.forms import LoginForm
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('login/', CustomLoginView.as_view(redirect_authenticated_user=True, template_name='users/login.html',
                                           authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    path('password-reset/', ResetPasswordView.as_view(), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-confirm/', auth_views.PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('password-change/', ChangePasswordView.as_view(), name='password_change'),
    path('', include('post.urls')),
    path('', include('cart.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from .views import (file_upload, user_posts, explore, user_profile,
                    delete_view, modify_post, post_view)

app_name = 'post'

urlpatterns = [
    path('post/', file_upload, name='user-post'),
    path('explore/', explore, name='explore'),
    path('user/', user_posts, name='user-file'),
    path('profile/<str:pk>/', user_profile, name='user-profile'),
    path('<id>/delete/', delete_view, name='post-delete'),
    path('<id>/modify/', modify_post, name='post-modify'),
    path('post_view/<str:pk>/', post_view, name='post-view'),

]

users/urls.py
from django.urls import path
from .views import home, RegisterView, profile


app_name = 'users'

urlpatterns = [
    path('', home, name='users-home'),
    path('users/', RegisterView.as_view(), name='users-register'),
    path('profile/', profile, name='users-profile')

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from PIL import Image
from django.utils.translation import gettext_lazy as _
# Create your models here.

class CustomUserManager(UserManager):
    def create_user(self, email, password=None, **extra_fields):
        first_name = extra_fields.get('first_name')
        if not first_name:
            raise ValueError('First name must be set.')
        last_name = extra_fields.get('last_name')
        if not last_name:
            raise ValueError('First name must be set.')

        if not email:
            raise ValueError('Last name must be set.')

        user = self.model(
            first_name=first_name,
            last_name=last_name,
            email=email,
            is_superuser=extra_fields.get('is_superuser', False),
            is_staff=extra_fields.get('is_staff', False),
        )
        user.set_password(password)
        user.save()

        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, password, **extra_fields)
    

class CustomAuthUser(AbstractUser):
    username = None
    first_name = models.CharField(_("first name"), max_length=150, blank=False, null=False)
    last_name = models.CharField(_("last name"), max_length=150, blank=False, null=False)
    email = models.EmailField(_("email address"), blank=False, null=False, unique=True)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = CustomUserManager()



# Extending User Modl Using a One-to-One Link
class Profile(models.Model):
    user = models.OneToOneField(CustomAuthUser, on_delete=models.CASCADE)
    avatar = models.ImageField(default='default.jpg', upload_to='profile_images')
    bio = models.TextField()

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super().save()

        img = Image.open(self.avatar.path)

        if img.height > 100 or img.width > 100:
            new_img = (300, 300)
            img.thumbnail(new_img)
            img.save(self.avatar.path)

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Profile


AuthUser = get_user_model()

class RegisterForm(UserCreationForm):

    class Meta:
        model = AuthUser
        fields = ['first_name', 'last_name', 'email']


class LoginForm(AuthenticationForm):

    remember_me = forms.BooleanField(required=False)

    class Meta:
        model = AuthUser
        fields = ['username', 'password', 'remember_me']


class UpdateUserForm(forms.ModelForm):

    class Meta:
        model = AuthUser
        fields = ['first_name', 'last_name', 'email']


class UpdateProfileForm(forms.ModelForm):
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form=control', 'rows': 5}))

    class Meta:
        model = Profile
        fields = ['avatar', 'bio']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from .forms import RegisterForm, LoginForm
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import UpdateProfileForm, UpdateUserForm

# Create your views here.


def home(request):
    return render(request, 'users/home.html')


class RegisterView(View):
    form_class = RegisterForm
    initial = {'key': 'value'}
    template_name = 'users/register.html'

    def dispatch(self, request, *args, **kwargs):
        # will redirect to the home page if user tries to access whiele logged in
        if request.user.is_authenticated:
            return redirect(to='/')

        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            messages.success(request, f'Account created for {email}')

            return redirect(to='login')

        return render(request, self.template_name, {'form': form})


class CustomLoginView(LoginView):
    form_class = LoginForm

    def form_valid(self, form):
        remember_me = form.cleaned_data.get('remember_me')

        if not remember_me:
            # Set session expiry to 0 seconds. So it will automatically close the session after the time has passed.
            self.request.session.set_expiry(0)

            # Set session as modified to force data updates/coockies.
            self.request.session.modified = True

        # else browser session will be as long as the session cookie time "SESSION_COOKIE_AGE" defined in settings.py
        return super(CustomLoginView, self).form_valid(form)


class ResetPasswordView(PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    subject_template_name = 'users/password_reset_subject'
    success_message = "We`ve emailed you instructions for setting your password ," \
                    "if an account exists with the email you provided. You should receive them shortly,"\
                    " If you don't receive an email, " \
                    "please make sure you've entered the address you registered with, and check your spam folder."

    success_url = reverse_lazy('users-home')


@login_required
def profile(request):
    if request.method == 'POST':
        user_form = UpdateUserForm(request.POST, instance=request.user.profile)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='users:users-profile')


    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, 'users/profile.html', {'user_form': user_form, 'profile_form': profile_form})


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'users/password_change.html'
    success_message = 'Successfully Changed Your Password'
    success_url = reverse_lazy('users-home')

users/templates/users/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://kit.fontawesome.com/bc434c6387.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <!-- FONTS -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Carrois+Gothic&display=swap" rel="stylesheet"> 
    <script type="text/javascript">
        var user = '{{request.user}}'
        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
    const csrftoken = getToken('csrftoken');

    function getCookie(name){
            // split cookie string and get all individual name=value pairs in an array

        var cookieArray = document.cookie.split(";");
        
        // Loop through the array of elements

        for(var i = 0; i < cookieArray.length; i++){
            var cookiePair = cookieArray[i].split('=');

            /* remove white space at the beginning of the cookie name
            and compare it with the given string */

            if(name == cookiePair[0].trim()){
                // Decode the cookie value and return
                return decodeURIComponent(cookiePair[1])
            }
        }

        // Return null if not found
        return null;
    }

    var cart = JSON.parse(getCookie('cart'))
    if(cart == undefined){
        cart = {}
        console.log('cart was created')
        document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
    }

    console.log('cart:', cart)



    </script>

    <title>{% block title %} {% endblock %} </title>
</head>
<body>
<!-- Navbar -->
{% include 'users/nav.html' %}
<!-- Navbar -->
<div class="page-container">
{% block content %}{% endblock %}
</div>


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!-- A plugin for password show/hide  -->
   <script src="https://unpkg.com/bootstrap-show-password@1.2.1/dist/bootstrap-show-password.min.js"></script>

    <script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
</body>
</html>

users/templates/users/home.html
{% extends 'users/base.html' %}

{% block title %} HOME {% endblock %}

{% block content %}


{% endblock %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% block title %} LogIN {% endblock %}

{% block content %}
<div class="form-upload">
        <header><a>Sign In</a></header>

        {% if form.errors %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <div id="form_errors">
                    {% for key, value in form.errors.items %}
                        <strong>{{ value }}</strong>
                    {% endfor %}
                </div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
            <form method="POST">
                {% csrf_token %}
                    <a href="{% url 'social:begin' 'github' %}"
                            class="btn btn-link btn-lg active btn-block">Sign in with GitHub</a>
                    <a href="#"
                            class="btn btn-link btn-lg active btn-block">Sign in with Google</a>
                            <p>Email:{{form.username}}</p>
                            <p>Pasword:{{form.password}}</p>
                    
                            <!-- Add a Remember me functionality -->
                            
                            <p><label> Remember me</label><span>{{ form.remember_me }}</span></p>
                            <button name="login" class="btn-profile" id="login">Sign in</button>
    
                <a href="{% url 'users:users-register' %}">Don't have an account yet? Go to signup</a><br>
                <a href="{% url 'password_reset' %}"><i>Forgot Password?</i></a>
                </form>
        
     </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "users/base.html" %}
{% block title %}Logout{% endblock title %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">You have been logged out</h5>

        </div>
    </div>


{% endblock content %}

users/templates/users/nav.html
<nav>
    <ul id="nav-title">
        <li><h1 ><a href="/" id="nav-title">E-ART</a></h1></li>
        <li><h3 ><a href="{% url 'post:explore' %}" >Explore</a></h3></li>
    </ul>
    
    
    <ul id="nav-user">
        
        {% if user.is_authenticated %}
        <li><a href="{% url 'users:users-profile' %}">Profile</a></li>
        <li><a href="{% url 'post:user-post' %}" >Post</a></li>
        <li><a href="{% url 'post:user-file' %}" >View posts</a></li>
        <li><a href="{% url 'logout' %}">Log out</a></li>
        <li><a href="{% url 'users:users-profile' %}" id="user"><img src="{{user.profile.avatar.url}}" class="avatar" width="30px">
        </a></li>
        {% else %}
        <li><a href="{% url 'login' %}" class="nav-item ">
            Login
          </a></li>
          <li><a href="{% url 'users:users-register' %}" class="nav-item nav-link">
    
            Sign up for free
         
          </a></li>
          {% endif %}
          <li><a href="{% url 'cart:cart-summary' %}" id="shopping"><i class="fa-solid fa-cart-shopping"></i></a></li>
    </ul>
</nav>

<!-- 
<script>
    const clicked = document.querySelectorAll('#nav-user a')

    for(var i = 0; i < clicked.length; i++) {
        clicked[i].addEventListener('click', function(e){
            clicked[i].classList.add('click')
            console.log('button clicked')
        })
    }

</script> -->

users/templates/users/password_change.html
{% extends "users/base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_old_password">Old Password</label>
                                                <input type="password" name="old_password" autocomplete="new-password"
                                                       class="form-control" required id="id_old_password"
                                                       placeholder="Enter Old Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter New Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm New Password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Update Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/password_reset.html
{% extends "users/base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:users-register' %}">Create A New Account</a><br><br>
                                <a href="{% url 'login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends "users/base.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "users/base.html" %}
{% block title %} Password Reset {% endblock title%}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if validlink %}
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Reset Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Reset Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    {% else %}
                    <div class="alert alert-warning">
                        The password reset link was invalid, possibly because it has already been used.
                        Please request a new password reset.
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} Django Registration/Login App Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The Developer
{% endautoescape %}